// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLk3YJCDdfkUeCrrelZTaAC3Wdbi_3o1A',
    appId: '1:717582476550:web:a0f28c37f4e4180228aa87',
    messagingSenderId: '717582476550',
    projectId: 'habit-tracker-bc23d',
    authDomain: 'habit-tracker-bc23d.firebaseapp.com',
    storageBucket: 'habit-tracker-bc23d.firebasestorage.app',
    measurementId: 'G-Z1P0P7KTQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7P4GCYJVpoBKYDyE8lthlaHSgkNPVcWw',
    appId: '1:717582476550:android:2e7cd2d4620b1aae28aa87',
    messagingSenderId: '717582476550',
    projectId: 'habit-tracker-bc23d',
    storageBucket: 'habit-tracker-bc23d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLAN73_5tlQdnOY-uYcV6afy3hf7R8W5w',
    appId: '1:717582476550:ios:2246f9c4188d239b28aa87',
    messagingSenderId: '717582476550',
    projectId: 'habit-tracker-bc23d',
    storageBucket: 'habit-tracker-bc23d.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLAN73_5tlQdnOY-uYcV6afy3hf7R8W5w',
    appId: '1:717582476550:ios:2246f9c4188d239b28aa87',
    messagingSenderId: '717582476550',
    projectId: 'habit-tracker-bc23d',
    storageBucket: 'habit-tracker-bc23d.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLk3YJCDdfkUeCrrelZTaAC3Wdbi_3o1A',
    appId: '1:717582476550:web:03e572e3ee5305d328aa87',
    messagingSenderId: '717582476550',
    projectId: 'habit-tracker-bc23d',
    authDomain: 'habit-tracker-bc23d.firebaseapp.com',
    storageBucket: 'habit-tracker-bc23d.firebasestorage.app',
    measurementId: 'G-P200CWB84Y',
  );
}
